// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr15yMeMDPkcIRZ-xt4iaRyQuR_wTtpvo',
    appId: '1:430348796798:web:dc9e4ebdfadc64d973692f',
    messagingSenderId: '430348796798',
    projectId: 'messenger-app-6910a',
    authDomain: 'messenger-app-6910a.firebaseapp.com',
    storageBucket: 'messenger-app-6910a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm7pWq0ph4pD4E2dobrYSFI6vVXJQfMoo',
    appId: '1:430348796798:android:1dc835770043f66173692f',
    messagingSenderId: '430348796798',
    projectId: 'messenger-app-6910a',
    storageBucket: 'messenger-app-6910a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAXEKHKn7nzDy11A5XW4gPBbbUJNr2u8Q',
    appId: '1:430348796798:ios:026240850ea5e99b73692f',
    messagingSenderId: '430348796798',
    projectId: 'messenger-app-6910a',
    storageBucket: 'messenger-app-6910a.firebasestorage.app',
    iosBundleId: 'com.example.messengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAXEKHKn7nzDy11A5XW4gPBbbUJNr2u8Q',
    appId: '1:430348796798:ios:026240850ea5e99b73692f',
    messagingSenderId: '430348796798',
    projectId: 'messenger-app-6910a',
    storageBucket: 'messenger-app-6910a.firebasestorage.app',
    iosBundleId: 'com.example.messengerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr15yMeMDPkcIRZ-xt4iaRyQuR_wTtpvo',
    appId: '1:430348796798:web:3a0a246c598c79ff73692f',
    messagingSenderId: '430348796798',
    projectId: 'messenger-app-6910a',
    authDomain: 'messenger-app-6910a.firebaseapp.com',
    storageBucket: 'messenger-app-6910a.firebasestorage.app',
  );
}
